add more tests and booting mongo as replica set (#39)
* use connect helper in tests

* configure replica set

* check that mocks are generated properly

* cancel workflows if new changes

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -10,10 +10,14 @@ on:
   schedule:
     - cron: "0 0 * * 0"
 
+concurrency:
+  group: ${{ format('{0}-{1}', github.workflow, github.head_ref) }}
+  cancel-in-progress: true
+
 env:
-  GO: 1.17
-  MONGO_USERNAME: admin
-  MONGO_PASSWORD: adminpass
+  GO: "1.17"
+  MONGO_USERNAME: "admin"
+  MONGO_PASSWORD: "adminpass"
 
 jobs:
   CodeQL:
@@ -36,16 +40,6 @@ jobs:
 
   UnitTests:
     runs-on: ubuntu-latest
-
-    services:
-      mongo:
-        image: mongo
-        ports:
-          - 27017:27017
-        env:
-          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_USERNAME }}
-          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_PASSWORD }}
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -55,9 +49,14 @@ jobs:
         with:
           go-version: ${{ env.GO }}
 
+      - name: Build and Run MongoDB
+        run: make run-docker
+        env:
+          SLEEP: 10
+
       - name: Run Unit Tests
         env:
-          MONGO_URI: "mongodb://${{ env.MONGO_USERNAME }}:${{ env.MONGO_PASSWORD }}@localhost/?authSource=admin"
+          MONGO_URI: "mongodb://${{ env.MONGO_USERNAME }}:${{ env.MONGO_PASSWORD }}@127.0.0.1:27888/?authSource=admin&directConnection=true"
         run: go test -race -cover -coverprofile=coverage.out -covermode=atomic
 
       - name: Codecov
@@ -83,3 +82,27 @@ jobs:
           version: latest
           skip-build-cache: true
           skip-go-installation: true
+
+  Mocks:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Install Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: ${{ env.GO }}
+
+      - name: Generate Mocks
+        run: make go-install generate-mocks
+
+      - name: Checking Git
+        run: |
+          DELTA="$(git status --short)"
+          if [ -n "${DELTA}" ]
+          then
+            echo "::error title=Mocks are outdated::Please run 'make generate-mocks' to re-generate the mocks"
+            exit 1
+          fi
